name: AskTheOracle
favicon: null
layout_spectrum: 0.00999001320451498
typography_spectrum: 0.17709382786415517
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010066'
    - '#ffffff'
    - '#403f8f'
    - '#a4a3ce'
    - '#6d6c99'
  brandStrength: 0
  lightness: 0.8385079849977046
  saturation: 0.4473472668323666
  rhythmicContrast: 0.8054828171152622
purpose: []
