name: AskTheOracle
favicon: null
layout_spectrum: 0.75652
typography_spectrum: 0.2485
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010066'
    - '#ffffff'
    - '#403f8f'
    - '#a4a3ce'
    - '#6d6c99'
  brandStrength: 0.375
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
